apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi
