apiVersion: v1
kind: Pod
metadata:
  name: taint-test
  namespace: dev
spec:
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "ecommerce"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx:alpine
